services:
  redis-1:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 7001 --cluster-announce-hostname host.docker.internal --cluster-announce-port 7001 --cluster-announce-bus-port 17001
    ports:
      - "7001:7001"
      - "17001:17001"

  redis-2:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 7002 --cluster-announce-hostname host.docker.internal --cluster-announce-port 7002 --cluster-announce-bus-port 17002
    ports:
      - "7002:7002"
      - "17002:17002"

  redis-3:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 7003 --cluster-announce-hostname host.docker.internal --cluster-announce-port 7003 --cluster-announce-bus-port 17003
    ports:
      - "7003:7003"
      - "17003:17003"

  redis-4:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 7004 --cluster-announce-hostname host.docker.internal --cluster-announce-port 7004 --cluster-announce-bus-port 17004
    ports:
      - "7004:7004"
      - "17004:17004"

  redis-5:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 7005 --cluster-announce-hostname host.docker.internal --cluster-announce-port 7005 --cluster-announce-bus-port 17005
    ports:
      - "7005:7005"
      - "17005:17005"

  redis-6:
    image: redis:7
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 7006 --cluster-announce-hostname host.docker.internal --cluster-announce-port 7006 --cluster-announce-bus-port 17006
    ports:
      - "7006:7006"
      - "17006:17006"
